env: dev
replicas: 2
resources:
    cpu: 80
    memory: 80
autoscaling: 
    enabled: true
    min: 2
    max: 6
container:
    name: identity
    image: solinx/combatanalysisidentity
    port: 80
service:
    port: 80
    targetPort: 8080
    nodePort: 30101
ingress:
    host: identity.analysis.com
    port: 80