env: dev
replicas: 2
autoscaling: 
    enabled: true
    min: 2
    max: 6
resources:
    cpu: 80
    memory: 80
container:
    name: identity
    image: solinx/identity
    tag: latest
    port: 80
service:
    protocol: TCP
    port: 80
    targetPort: 80
ingress:
    appName: solinx.analysis.identity
    port: 80