//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CombatAnalysis.App.Localizations.Resources.DamageDoneDetails {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CombatAnalysis.App.Localizations.Resources.DamageDoneDetails.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ср. значение.
        /// </summary>
        public static string AverageValue {
            get {
                return ResourceManager.GetString("AverageValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общий.
        /// </summary>
        public static string Common {
            get {
                return ResourceManager.GetString("Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Примен. закл..
        /// </summary>
        public static string CountOfSkills {
            get {
                return ResourceManager.GetString("CountOfSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Урон.
        /// </summary>
        public static string Damage {
            get {
                return ResourceManager.GetString("Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Урон в сек..
        /// </summary>
        public static string DamagePerSec {
            get {
                return ResourceManager.GetString("DamagePerSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Макс. значение.
        /// </summary>
        public static string MaxValue {
            get {
                return ResourceManager.GetString("MaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мин. значение.
        /// </summary>
        public static string MinValue {
            get {
                return ResourceManager.GetString("MinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подробнее.
        /// </summary>
        public static string MoreDetails {
            get {
                return ResourceManager.GetString("MoreDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать крит.
        /// </summary>
        public static string ShowCritDamage {
            get {
                return ResourceManager.GetString("ShowCritDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать уклонение.
        /// </summary>
        public static string ShowDodge {
            get {
                return ResourceManager.GetString("ShowDodge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать фильтры.
        /// </summary>
        public static string ShowFilters {
            get {
                return ResourceManager.GetString("ShowFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать иммун.
        /// </summary>
        public static string ShowImmune {
            get {
                return ResourceManager.GetString("ShowImmune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать промахи.
        /// </summary>
        public static string ShowMiss {
            get {
                return ResourceManager.GetString("ShowMiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать парирование.
        /// </summary>
        public static string ShowParry {
            get {
                return ResourceManager.GetString("ShowParry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать сопр..
        /// </summary>
        public static string ShowResist {
            get {
                return ResourceManager.GetString("ShowResist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Источник.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Анализ нанесенного урона.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всего:.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип.
        /// </summary>
        public static string TypeOf {
            get {
                return ResourceManager.GetString("TypeOf", resourceCulture);
            }
        }
    }
}
