//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CombatAnalysis.App.Localizations.Resources.DamageDoneDetails {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource___Copy {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource___Copy() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CombatAnalysis.App.Localizations.Resources.DamageDoneDetails.Resource - Copy", typeof(Resource___Copy).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average value.
        /// </summary>
        public static string AverageValue {
            get {
                return ResourceManager.GetString("AverageValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string Common {
            get {
                return ResourceManager.GetString("Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count of skills.
        /// </summary>
        public static string CountOfSkills {
            get {
                return ResourceManager.GetString("CountOfSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crit damage.
        /// </summary>
        public static string CritDamage {
            get {
                return ResourceManager.GetString("CritDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage.
        /// </summary>
        public static string Damage {
            get {
                return ResourceManager.GetString("Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage per sec..
        /// </summary>
        public static string DamagePerSec {
            get {
                return ResourceManager.GetString("DamagePerSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodge.
        /// </summary>
        public static string Dodge {
            get {
                return ResourceManager.GetString("Dodge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        public static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immune.
        /// </summary>
        public static string Immune {
            get {
                return ResourceManager.GetString("Immune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        public static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. value.
        /// </summary>
        public static string MaxValue {
            get {
                return ResourceManager.GetString("MaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min. value.
        /// </summary>
        public static string MinValue {
            get {
                return ResourceManager.GetString("MinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miss.
        /// </summary>
        public static string Miss {
            get {
                return ResourceManager.GetString("Miss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More details.
        /// </summary>
        public static string MoreDetails {
            get {
                return ResourceManager.GetString("MoreDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parry.
        /// </summary>
        public static string Parry {
            get {
                return ResourceManager.GetString("Parry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periodic damage.
        /// </summary>
        public static string PeriodicDamage {
            get {
                return ResourceManager.GetString("PeriodicDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        public static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev.
        /// </summary>
        public static string Prev {
            get {
                return ResourceManager.GetString("Prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resist.
        /// </summary>
        public static string Resist {
            get {
                return ResourceManager.GetString("Resist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crit.
        /// </summary>
        public static string ShowCritDamage {
            get {
                return ResourceManager.GetString("ShowCritDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodge.
        /// </summary>
        public static string ShowDodge {
            get {
                return ResourceManager.GetString("ShowDodge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        public static string ShowFilters {
            get {
                return ResourceManager.GetString("ShowFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immune.
        /// </summary>
        public static string ShowImmune {
            get {
                return ResourceManager.GetString("ShowImmune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miss.
        /// </summary>
        public static string ShowMiss {
            get {
                return ResourceManager.GetString("ShowMiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parry.
        /// </summary>
        public static string ShowParry {
            get {
                return ResourceManager.GetString("ShowParry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pets and creatures.
        /// </summary>
        public static string ShowPets {
            get {
                return ResourceManager.GetString("ShowPets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resist.
        /// </summary>
        public static string ShowResist {
            get {
                return ResourceManager.GetString("ShowResist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzing of damage done.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total:.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string TypeOf {
            get {
                return ResourceManager.GetString("TypeOf", resourceCulture);
            }
        }
    }
}
