CREATE PROCEDURE [dbo].[InsertIntoCombatLog]
	@Name NVARCHAR (MAX),
	@Date DATETIMEOFFSET (7),
	@IsReady BIT
AS
	DECLARE @OutputTbl TABLE (Id INT,Name NVARCHAR (MAX),Date DATETIMEOFFSET (7),IsReady BIT)
	INSERT INTO CombatLog
	OUTPUT INSERTED.* INTO @OutputTbl
	VALUES (@Name,@Date,@IsReady)
	SELECT * FROM @OutputTbl
RETURN 0
