env: dev
resources:
    cpu: 80
    memory: 80
service:
    protocol: TCP
    port: 80
    targetPort: 80
app1:
    hostName: solinx.analysis.api.user
    name: user-api
    replicas: 2
    autoscaling: 
        enabled: true
        min: 2
        max: 6
    container:
        name: user-api
        image: solinx/user-api
        tag: latest
        port: 80
    ingress:
        port: 80
app2:
    hostName: solinx.analysis.api.communication
    name: communication-api
    replicas: 2
    autoscaling: 
        enabled: true
        min: 2
        max: 6
    container:
        name: communication-api
        image: solinx/communication-api
        tag: latest
        port: 80
    ingress:
        port: 80
app3:
    hostName: solinx.analysis.api.chat
    name: chat-api
    replicas: 2
    autoscaling: 
        enabled: true
        min: 2
        max: 6
    container:
        name: chat-api
        image: solinx/chat-api
        tag: latest
        port: 80
    ingress:
        port: 80
app4:
    hostName: solinx.analysis.api.parser
    name: combat-parser-api
    replicas: 2
    autoscaling: 
        enabled: true
        min: 2
        max: 6
    container:
        name: combat-parser-api
        image: solinx/combat-parser-api
        tag: latest
        port: 80
    ingress:
        port: 80