env: dev
resources:
    cpu: 80
    memory: 80
service:
    protocol: TCP
    port: 80
    targetPort: 8080
app1:
    hostName: api.analysis.user.com
    name: user
    replicas: 2
    autoscaling: 
        enabled: true
        min: 2
        max: 6
    container:
        name: user
        image: solinx/combatanalysisuserapi
        tag: 0.3.1
        port: 80
    ingress:
        port: 80
    service:
        nodePort: 30001
app2:
    hostName: api.analysis.communication.com
    name: communication
    replicas: 2
    autoscaling: 
        enabled: false
        min: 2
        max: 6
    container:
        name: communication
        image: solinx/combatanalysiscommunicationapi
        tag: 0.3.0
        port: 80
    ingress:
        port: 80
    service:
        nodePort: 30002
app3:
    hostName: api.analysis.chat.com
    name: chat
    replicas: 2
    autoscaling: 
        enabled: false
        min: 2
        max: 6
    container:
        name: chat
        image: solinx/combatanalysischatapi
        tag: 0.3.0
        port: 80
    ingress:
        port: 80
    service:
        nodePort: 30003
app4:
    hostName: api.analysis.parser.com
    name: combat-parser
    replicas: 2
    autoscaling: 
        enabled: false
        min: 2
        max: 6
    container:
        name: combat-parser
        image: solinx/combatanalysiscombatparserapi
        tag: 0.3.0
        port: 80
    ingress:
        port: 80
    service:
        nodePort: 30004
app5:
    hostName: api.analysis.health.com
    name: health
    replicas: 2
    autoscaling: 
        enabled: false
        min: 2
        max: 6
    container:
        name: health
        image: solinx/healthapi
        tag: 0.2.0
        port: 80
    ingress:
        port: 80
    service:
        nodePort: 30005