apiVersion: v1
kind: Secret
metadata:
  name: authentication
type: Opaque
data:
  issuer: aHR0cHM6Ly9pZGVudGl0eS5hbmFseXNpcy5jb20v
  issuerSigningKey: YUZvL1ArME04VFJLaGprSWhqUjErMVkvYjc3ZVNsOUV3ZGoyZTNoU3hSUT0=
  authority: aHR0cHM6Ly9pZGVudGl0eS5hbmFseXNpcy5jb20v