apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.communication.name }}-deployment
  labels:
    app: {{ .Release.Name }}
    env: {{ .Values.env }}
    owner: OlegFedosov
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.communication.replicas }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.communication.name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.communication.name }}
    spec:
      containers:
        - name: {{ .Values.communication.container.name }}
          image: {{ .Values.communication.container.image }}:{{ .Values.imageTags.api.communication }}
          ports:
            - containerPort: {{ .Values.communication.container.port }}
          env:
           - name: ASPNETCORE_ENVIRONMENT
             value: {{ .Values.env }}
           - name: Database_Name
             value: "MSSQL"
           - name: Database_DataProcessingType
             value: "StoredProcedure"
           - name: ConnectionStrings_DefaultConnection
             value: "Server=host.docker.internal,1433;Database=Combat_Analysis.Communication;User Id=sa;Password=Oleg123;Integrated Security=False;Connect Timeout=120;Encrypt=True;Trust Server Certificate=True;Application Intent=ReadWrite;Multi Subnet Failover=False"
           - name: ConnectionStrings_Firebase
             value: "https://detailsanalysisgamecombatlogs-default-rtdb.firebaseio.com/"
           - name: API_Identity
             value: "https://identity.analysis.com/"
           - name: Authentication_Issuer
             value: "https://identity.analysis.com/"
           - name: Authentication_IssuerSigningKey
             value: "aFo/P+0M8TRKhjkIhjR1+1Y/b77eSl9Ewdj2e3hSxRQ="
           - name: Authentication_Authority
             value: "https://identity.analysis.com/"
           - name: Authentication_Client_WebClientId
             value: "client1"
           - name: Authentication_Client_DesktopClientId
             value: "client2"
           - name: Authentication_Client_Scope
             value: "client1scope"