{{- if .Values.app1.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-{{ .Values.app1.name }}-deployment-autoscaling
spec:
  scaleTargetRef:
    apiVersion: web-app/v1
    kind: Deployment
    name: {{ .Release.Name }}-{{ .Values.app1.name }}-deployment
  minReplicas: {{ .Values.app1.autoscaling.min }}
  maxReplicas:  {{ .Values.app1.autoscaling.max }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.resources.cpu }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.resources.memory }}
{{- end }}