apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.user.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-{{ .Values.user.name }}-service
                port:
                  number: {{ .Values.user.ingress.port }}
    - host: {{ .Values.communication.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-{{ .Values.communication.name }}-service
                port:
                  number: {{ .Values.communication.ingress.port }}
    - host: {{ .Values.chat.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-{{ .Values.chat.name }}-service
                port:
                  number: {{ .Values.chat.ingress.port }}
    - host: {{ .Values.parser.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-{{ .Values.parser.name }}-service
                port:
                  number: {{ .Values.parser.ingress.port }}
    - host: {{ .Values.health.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-{{ .Values.health.name }}-service
                port:
                  number: {{ .Values.health.ingress.port }}