apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
spec:
  tls:
  - hosts:
      - {{ .Values.user.ingress.host }}
      - {{ .Values.communication.ingress.host }}
      - {{ .Values.chat.ingress.host }}
      - {{ .Values.health.ingress.host }}
    secretName: tls-secret
  rules:
    - host: {{ .Values.user.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-{{ .Values.user.name }}-service
                port:
                  number: {{ .Values.user.service.targetPort }}
    - host: {{ .Values.communication.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-{{ .Values.communication.name }}-service
                port:
                  number: {{ .Values.communication.service.targetPort }}
    - host: {{ .Values.chat.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-{{ .Values.chat.name }}-service
                port:
                  number: {{ .Values.chat.service.targetPort }}
    - host: {{ .Values.health.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-{{ .Values.health.name }}-service
                port:
                  number: {{ .Values.health.service.targetPort }}