//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CombatAnalysis.App.Localizations.Resources.Chat {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CombatAnalysis.App.Localizations.Resources.Chat.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add user.
        /// </summary>
        public static string AddUser {
            get {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach document.
        /// </summary>
        public static string AttachDocument {
            get {
                return ResourceManager.GetString("AttachDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new group chat.
        /// </summary>
        public static string CreateNewGroupChat {
            get {
                return ResourceManager.GetString("CreateNewGroupChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create voice message.
        /// </summary>
        public static string CreateVoiceMessage {
            get {
                return ResourceManager.GetString("CreateVoiceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group chats.
        /// </summary>
        public static string GroupChats {
            get {
                return ResourceManager.GetString("GroupChats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading failed.
        /// </summary>
        public static string LoadingFailed {
            get {
                return ResourceManager.GetString("LoadingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for a group chat.
        /// </summary>
        public static string LookingForGroupChat {
            get {
                return ResourceManager.GetString("LookingForGroupChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any group chats.
        /// </summary>
        public static string NoGroupChats {
            get {
                return ResourceManager.GetString("NoGroupChats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any personal messages.
        /// </summary>
        public static string NoPersonalMessages {
            get {
                return ResourceManager.GetString("NoPersonalMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal messages.
        /// </summary>
        public static string PersonalMessages {
            get {
                return ResourceManager.GetString("PersonalMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh the group chats.
        /// </summary>
        public static string RefreshGroupChats {
            get {
                return ResourceManager.GetString("RefreshGroupChats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh the personal messages.
        /// </summary>
        public static string RefreshPersonalMessages {
            get {
                return ResourceManager.GetString("RefreshPersonalMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove user.
        /// </summary>
        public static string RemoveUser {
            get {
                return ResourceManager.GetString("RemoveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search user.
        /// </summary>
        public static string SearchUser {
            get {
                return ResourceManager.GetString("SearchUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select any chat for chatting.
        /// </summary>
        public static string SelectChatForTalking {
            get {
                return ResourceManager.GetString("SelectChatForTalking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send message.
        /// </summary>
        public static string SendMessage {
            get {
                return ResourceManager.GetString("SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all.
        /// </summary>
        public static string ShowAll {
            get {
                return ResourceManager.GetString("ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start dialog.
        /// </summary>
        public static string StartDialog {
            get {
                return ResourceManager.GetString("StartDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typing message....
        /// </summary>
        public static string TypingMessage {
            get {
                return ResourceManager.GetString("TypingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User added.
        /// </summary>
        public static string UserAdded {
            get {
                return ResourceManager.GetString("UserAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We can&apos;t add a new user.
        /// </summary>
        public static string UserAddFailed {
            get {
                return ResourceManager.GetString("UserAddFailed", resourceCulture);
            }
        }
    }
}
