//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CombatAnalysis.App.Localizations.Resources.GeneralAnalysis {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CombatAnalysis.App.Localizations.Resources.GeneralAnalysis.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All combats saved!.
        /// </summary>
        public static string AllCombatsSaved {
            get {
                return ResourceManager.GetString("AllCombatsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Av. indicator damage.
        /// </summary>
        public static string AverageDamage {
            get {
                return ResourceManager.GetString("AverageDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Av. indicator damage per sec..
        /// </summary>
        public static string AverageDamagePerSecond {
            get {
                return ResourceManager.GetString("AverageDamagePerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Av. indicator damage taken.
        /// </summary>
        public static string AverageDamageTaken {
            get {
                return ResourceManager.GetString("AverageDamageTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Av. indicator damage taken per sec..
        /// </summary>
        public static string AverageDamageTakenPerSecond {
            get {
                return ResourceManager.GetString("AverageDamageTakenPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Av. indicator heal.
        /// </summary>
        public static string AverageHeal {
            get {
                return ResourceManager.GetString("AverageHeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Av. indicator heal per sec..
        /// </summary>
        public static string AverageHealPerSecond {
            get {
                return ResourceManager.GetString("AverageHealPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Av. indicator resources recovery.
        /// </summary>
        public static string AverageResources {
            get {
                return ResourceManager.GetString("AverageResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Av. indicator resources recovery per sec..
        /// </summary>
        public static string AverageResourcesPerSecond {
            get {
                return ResourceManager.GetString("AverageResourcesPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffs.
        /// </summary>
        public static string Buffs {
            get {
                return ResourceManager.GetString("Buffs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage.
        /// </summary>
        public static string Damage {
            get {
                return ResourceManager.GetString("Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage taken.
        /// </summary>
        public static string DamageTaken {
            get {
                return ResourceManager.GetString("DamageTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deaths.
        /// </summary>
        public static string Deaths {
            get {
                return ResourceManager.GetString("Deaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defeat.
        /// </summary>
        public static string Defeat {
            get {
                return ResourceManager.GetString("Defeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enemy.
        /// </summary>
        public static string Enemy {
            get {
                return ResourceManager.GetString("Enemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healing.
        /// </summary>
        public static string Healing {
            get {
                return ResourceManager.GetString("Healing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H.
        /// </summary>
        public static string Heroic {
            get {
                return ResourceManager.GetString("Heroic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index of death.
        /// </summary>
        public static string IndexOfDeath {
            get {
                return ResourceManager.GetString("IndexOfDeath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t save your data. Repeat?.
        /// </summary>
        public static string LoadingFailed {
            get {
                return ResourceManager.GetString("LoadingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. indicator damage.
        /// </summary>
        public static string MaxDamage {
            get {
                return ResourceManager.GetString("MaxDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. indicator damage per sec..
        /// </summary>
        public static string MaxDamagePerSecond {
            get {
                return ResourceManager.GetString("MaxDamagePerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. indicator damage taken.
        /// </summary>
        public static string MaxDamageTaken {
            get {
                return ResourceManager.GetString("MaxDamageTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. indicator damage taken per sec..
        /// </summary>
        public static string MaxDamageTakenPerSecond {
            get {
                return ResourceManager.GetString("MaxDamageTakenPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. indicator heal.
        /// </summary>
        public static string MaxHeal {
            get {
                return ResourceManager.GetString("MaxHeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. indicator heal per sec..
        /// </summary>
        public static string MaxHealPerSecond {
            get {
                return ResourceManager.GetString("MaxHealPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. indicator resources recovery.
        /// </summary>
        public static string MaxResources {
            get {
                return ResourceManager.GetString("MaxResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. indicator resources recovery per sec..
        /// </summary>
        public static string MaxResourcesPerSecond {
            get {
                return ResourceManager.GetString("MaxResourcesPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        public static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not ready.
        /// </summary>
        public static string NotReady {
            get {
                return ResourceManager.GetString("NotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat.
        /// </summary>
        public static string Repeat {
            get {
                return ResourceManager.GetString("Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        public static string Resources {
            get {
                return ResourceManager.GetString("Resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show average information for all combats.
        /// </summary>
        public static string ShowAverageInform {
            get {
                return ResourceManager.GetString("ShowAverageInform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzing.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded:.
        /// </summary>
        public static string Uploaded {
            get {
                return ResourceManager.GetString("Uploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading....
        /// </summary>
        public static string Uploading {
            get {
                return ResourceManager.GetString("Uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win.
        /// </summary>
        public static string Win {
            get {
                return ResourceManager.GetString("Win", resourceCulture);
            }
        }
    }
}
