apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-websockets
spec:
  podSelector:
    matchLabels:
      app: web-app
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: web-app
    ports:
    - protocol: TCP
      port: 80
     