env: dev
replicas: 2
autoscaling: 
    enabled: false
    min: 2
    max: 6
resources:
    cpu: 80
    memory: 80
container:
    name: solinx-analysis-web-app
    image: solinx/combatanalysiswebapp
    tag: 0.3.20
    port: 80
service:
    protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30201
ingress:
    host: encounters.analysis.com
    port: 80