apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: web-app-hpa
  namespace: default
spec:
  maxReplicas: 4
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-app
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtiliation: 50
  - type: Resource
    resource:
      name: memory
      targetAverageUtiliation: 50