/*
Deployment script for CombatAnalysis.DataBase

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "CombatAnalysis.DataBase"
:setvar DefaultFilePrefix "CombatAnalysis.DataBase"
:setvar DefaultDataPath "C:\Users\yanez\AppData\Local\Microsoft\VisualStudio\SSDT\CombatAnalysis"
:setvar DefaultLogPath "C:\Users\yanez\AppData\Local\Microsoft\VisualStudio\SSDT\CombatAnalysis"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
/*
The column [dbo].[GroupChatMessage].[Username] is being dropped, data loss could occur.
*/

IF EXISTS (select top 1 1 from [dbo].[GroupChatMessage])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
/*
The column [dbo].[PersonalChat].[CompanionUsername] is being dropped, data loss could occur.

The column [dbo].[PersonalChat].[InitiatorUsername] is being dropped, data loss could occur.
*/

IF EXISTS (select top 1 1 from [dbo].[PersonalChat])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
/*
The column [dbo].[PersonalChatMessage].[Username] is being dropped, data loss could occur.
*/

IF EXISTS (select top 1 1 from [dbo].[PersonalChatMessage])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
PRINT N'Altering Table [dbo].[GroupChatMessage]...';


GO
ALTER TABLE [dbo].[GroupChatMessage] DROP COLUMN [Username];


GO
ALTER TABLE [dbo].[GroupChatMessage]
    ADD [OwnerId] NVARCHAR (MAX) NULL;


GO
PRINT N'Altering Table [dbo].[PersonalChat]...';


GO
ALTER TABLE [dbo].[PersonalChat] DROP COLUMN [CompanionUsername], COLUMN [InitiatorUsername];


GO
PRINT N'Altering Table [dbo].[PersonalChatMessage]...';


GO
ALTER TABLE [dbo].[PersonalChatMessage] DROP COLUMN [Username];


GO
ALTER TABLE [dbo].[PersonalChatMessage]
    ADD [OwnerId] NVARCHAR (MAX) NULL;


GO
PRINT N'Altering Procedure [dbo].[InsertIntoGroupChatMessage]...';


GO
ALTER PROCEDURE [dbo].[InsertIntoGroupChatMessage]
	@Message NVARCHAR (MAX),
	@Time TIME (7),
	@GroupChatId INT,
	@OwnerId NVARCHAR (MAX)
AS
	DECLARE @OutputTbl TABLE (Id INT,Message NVARCHAR (MAX),Time TIME (7),GroupChatId INT, OwnerId NVARCHAR (MAX))
	INSERT INTO GroupChatMessage
	OUTPUT INSERTED.* INTO @OutputTbl
	VALUES (@Message,@Time,@GroupChatId,@OwnerId)
	SELECT * FROM @OutputTbl
RETURN 0
GO
PRINT N'Altering Procedure [dbo].[UpdateGroupChatMessage]...';


GO
ALTER PROCEDURE [dbo].[UpdateGroupChatMessage]
	@Id INT,
	@Message NVARCHAR (MAX),
	@Time TIME (7),
	@GroupChatId INT,
	@OwnerId NVARCHAR (MAX)
AS
	UPDATE GroupChatMessage
	SET Message = @Message,Time = @Time,GroupChatId = @GroupChatId,OwnerId = @OwnerId
	WHERE Id = @Id
RETURN 0
GO
PRINT N'Altering Procedure [dbo].[InsertIntoPersonalChat]...';


GO
ALTER PROCEDURE [dbo].[InsertIntoPersonalChat]
	@LastMessage NVARCHAR (MAX),
	@InitiatorId NVARCHAR (MAX),
	@CompanionId NVARCHAR (MAX)
AS
	DECLARE @OutputTbl TABLE (Id INT,LastMessage NVARCHAR (MAX),InitiatorId NVARCHAR (MAX),CompanionId NVARCHAR (MAX))
	INSERT INTO PersonalChat
	OUTPUT INSERTED.* INTO @OutputTbl
	VALUES (@LastMessage,@InitiatorId,@CompanionId)
	SELECT * FROM @OutputTbl
RETURN 0
GO
PRINT N'Altering Procedure [dbo].[UpdatePersonalChat]...';


GO
ALTER PROCEDURE [dbo].[UpdatePersonalChat]
	@Id INT,
	@LastMessage NVARCHAR (MAX),
	@InitiatorId NVARCHAR (MAX),
	@CompanionId NVARCHAR (MAX)
AS
	UPDATE PersonalChat
	SET LastMessage = @LastMessage,InitiatorId = @InitiatorId,CompanionId = @CompanionId
	WHERE Id = @Id
RETURN 0
GO
PRINT N'Altering Procedure [dbo].[InsertIntoPersonalChatMessage]...';


GO
ALTER PROCEDURE [dbo].[InsertIntoPersonalChatMessage]
	@Message NVARCHAR (MAX),
	@Time TIME (7),
	@PersonalChatId INT,
	@OwnerId NVARCHAR (MAX)
AS
	DECLARE @OutputTbl TABLE (Id INT,Message NVARCHAR (MAX),Time TIME (7),PersonalChatId INT, wnerId NVARCHAR (MAX))
	INSERT INTO PersonalChatMessage
	OUTPUT INSERTED.* INTO @OutputTbl
	VALUES (@Message,@Time,@PersonalChatId,@OwnerId)
	SELECT * FROM @OutputTbl
RETURN 0
GO
PRINT N'Altering Procedure [dbo].[UpdatePersonalChatMessage]...';


GO
ALTER PROCEDURE [dbo].[UpdatePersonalChatMessage]
	@Id INT,
	@Message NVARCHAR (MAX),
	@Time TIME (7),
	@PersonalChatId INT,
	@OwnerId NVARCHAR (MAX)
AS 
	UPDATE PersonalChatMessage
	SET Message = @Message,Time = @Time,PersonalChatId = @PersonalChatId,OwnerId = @OwnerId
	WHERE Id = @Id
RETURN 0
GO
PRINT N'Refreshing Procedure [dbo].[DeleteGroupChatMessageById]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[DeleteGroupChatMessageById]';


GO
PRINT N'Refreshing Procedure [dbo].[GetAllGroupChatMessage]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[GetAllGroupChatMessage]';


GO
PRINT N'Refreshing Procedure [dbo].[GetGroupChatMessageById]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[GetGroupChatMessageById]';


GO
PRINT N'Refreshing Procedure [dbo].[DeletePersonalChatById]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[DeletePersonalChatById]';


GO
PRINT N'Refreshing Procedure [dbo].[GetAllPersonalChat]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[GetAllPersonalChat]';


GO
PRINT N'Refreshing Procedure [dbo].[GetPersonalChatById]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[GetPersonalChatById]';


GO
PRINT N'Refreshing Procedure [dbo].[DeletePersonalChatMessageById]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[DeletePersonalChatMessageById]';


GO
PRINT N'Refreshing Procedure [dbo].[GetAllPersonalChatMessage]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[GetAllPersonalChatMessage]';


GO
PRINT N'Refreshing Procedure [dbo].[GetPersonalChatMessageById]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[GetPersonalChatMessageById]';


GO
/*
Шаблон скрипта после развертывания							
--------------------------------------------------------------------------------------
 В данном файле содержатся инструкции SQL, которые будут добавлены в скрипт построения.		
 Используйте синтаксис SQLCMD для включения файла в скрипт после развертывания.			
 Пример:      :r .\myfile.sql								
 Используйте синтаксис SQLCMD для создания ссылки на переменную в скрипте после развертывания.		
 Пример:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/

-- CombatLog
insert into dbo.CombatLog
values ('Combat #1', '09.27.2022 10:15:00', 'TRUE')

-- Combat
insert into dbo.Combat
values ('Dungeon #1', 'Boss #1', 3000, 2500, 4000, 500, 0, 0, 'TRUE', '09.26.2022 11:10:00', '09.26.2022 11:12:00', 1)

---- CombatLogByUser
--insert into dbo.Combat
--values ('Dungeon #1', 'Boss #1', 3000, 2500, 4000, 500, 0, 0, 'TRUE', '09.26.2022 11:10:00', '09.26.2022 11:12:00', 1)

-- CombatPlayer
insert into dbo.CombatPlayer
values ('Player #1', 650, 2750, 4255, 3210, 0, 1)

-- DamageDone
insert into dbo.DamageDone
values (275, '00:35', 'Player #1', 'Enemy #1', 'Spell #1', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 1)

-- DamageDoneGeneral
insert into dbo.DamageDoneGeneral
values (2750, 943, 'Spell #1', 2, 0, 18, 275, 650, 462, 1)

-- DamageTaken
insert into dbo.DamageTaken
values (148, '00:29', 'Enemy #1', 'Player #1', 'Spell #1', 'FALSE', 0, 0, 24, 192, 20, 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'FALSE', 'TRUE', 1)

-- DamageTakenGeneral
insert into dbo.DamageTakenGeneral
values (3210, 745, 'Spell #1', 0, 0, 11, 411, 725, 568, 1)

-- HealDone
insert into dbo.HealDone
values (433, '00:30', 20, 513, 'Player #1', 'Player #2','Spell #1', 'FALSE', 'FALSE', 1)

-- HealDoneGeneral
insert into dbo.HealDoneGeneral
values (4255, 865, 'Spell #1', 0, 23, 411, 725, 568, 1)

-- ResourceRecovery
insert into dbo.ResourceRecovery
values (64, '00:26', 'Player #1', 1)

-- ResourceRecoveryGeneral
insert into dbo.ResourceRecoveryGeneral
values (650, 211, 'Spell #1', 9, 49, 227, 138, 1)
GO

GO
PRINT N'Update complete.';


GO
