//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CombatAnalysis.App.Localizations.Resources.DamageTakenDetails {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CombatAnalysis.App.Localizations.Resources.DamageTakenDetails.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absorption.
        /// </summary>
        public static string Absorption {
            get {
                return ResourceManager.GetString("Absorption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absorptioned: .
        /// </summary>
        public static string AbsorptionDetails {
            get {
                return ResourceManager.GetString("AbsorptionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average value.
        /// </summary>
        public static string AverageValue {
            get {
                return ResourceManager.GetString("AverageValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked: .
        /// </summary>
        public static string BlockDetails {
            get {
                return ResourceManager.GetString("BlockDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string Common {
            get {
                return ResourceManager.GetString("Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count of skills.
        /// </summary>
        public static string CountOfSkills {
            get {
                return ResourceManager.GetString("CountOfSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crushing damage.
        /// </summary>
        public static string CrushingDamage {
            get {
                return ResourceManager.GetString("CrushingDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage taken.
        /// </summary>
        public static string DamageTaken {
            get {
                return ResourceManager.GetString("DamageTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage taken per sec..
        /// </summary>
        public static string DamageTakenPerSec {
            get {
                return ResourceManager.GetString("DamageTakenPerSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodge.
        /// </summary>
        public static string Dodge {
            get {
                return ResourceManager.GetString("Dodge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enemy/Periodic damage.
        /// </summary>
        public static string EnemyOrPerDamage {
            get {
                return ResourceManager.GetString("EnemyOrPerDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. value.
        /// </summary>
        public static string MaxValue {
            get {
                return ResourceManager.GetString("MaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min. value.
        /// </summary>
        public static string MinValue {
            get {
                return ResourceManager.GetString("MinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miss.
        /// </summary>
        public static string Miss {
            get {
                return ResourceManager.GetString("Miss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mitigated: .
        /// </summary>
        public static string MitigateDetails {
            get {
                return ResourceManager.GetString("MitigateDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More details.
        /// </summary>
        public static string MoreDetails {
            get {
                return ResourceManager.GetString("MoreDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parry.
        /// </summary>
        public static string Parry {
            get {
                return ResourceManager.GetString("Parry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periodic damage.
        /// </summary>
        public static string PeriodicDamage {
            get {
                return ResourceManager.GetString("PeriodicDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        public static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real damage: .
        /// </summary>
        public static string RealDamageDetails {
            get {
                return ResourceManager.GetString("RealDamageDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resist.
        /// </summary>
        public static string Resist {
            get {
                return ResourceManager.GetString("Resist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resisted: .
        /// </summary>
        public static string ResistDetails {
            get {
                return ResourceManager.GetString("ResistDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show absorption.
        /// </summary>
        public static string ShowAbsorption {
            get {
                return ResourceManager.GetString("ShowAbsorption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show crush. damage.
        /// </summary>
        public static string ShowCrushingDamage {
            get {
                return ResourceManager.GetString("ShowCrushingDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show dodge.
        /// </summary>
        public static string ShowDodge {
            get {
                return ResourceManager.GetString("ShowDodge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show filters.
        /// </summary>
        public static string ShowFilters {
            get {
                return ResourceManager.GetString("ShowFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show immune.
        /// </summary>
        public static string ShowImmune {
            get {
                return ResourceManager.GetString("ShowImmune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show miss.
        /// </summary>
        public static string ShowMiss {
            get {
                return ResourceManager.GetString("ShowMiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show more informations.
        /// </summary>
        public static string ShowMoreInform {
            get {
                return ResourceManager.GetString("ShowMoreInform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show parry.
        /// </summary>
        public static string ShowParry {
            get {
                return ResourceManager.GetString("ShowParry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show resist.
        /// </summary>
        public static string ShowResist {
            get {
                return ResourceManager.GetString("ShowResist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzing of damage taken.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total:.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string TypeOf {
            get {
                return ResourceManager.GetString("TypeOf", resourceCulture);
            }
        }
    }
}
