apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: chat-api-hpa
  namespace: default
spec:
  maxReplicas: 4
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: chat-api
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtiliation: 25
  - type: Resource
    resource:
      name: memory
      targetAverageUtiliation: 25