name: Deploy master
on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:

    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Upload artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        path: 'businessCard/'

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: AKIAVGQFZJBSR3RRZXMU
        aws_secret_key: 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
        application_name: details-analysis
        environment_name: DetailsAnalysis
        version_label: 1236
        region: us-west-2
        deployment_package: src/CombatAnalysis.WebApp/CombatAnalysis.WebApp.csproj
